### ISSUE TITLE
Travis builds?

### ISSUE THREAD

**Issue by sckott** [ropensci/neotoma#160] opened 2014-12-16 17:45 UTC
@SimonGoring  travis builds are erroring https://travis-ci.org/ropensci/neotoma/builds/37320066  Does this indicate the pkg may not operate properly? or is it something minor, or specific to travis

**Comment by SimonGoring** [comment] 2015-01-07 21:25
I referenced this issue in commit c70a92a490d9e17affa122514a39501ed4dc9a26 Not sure if I did it right.

**Comment by SimonGoring** [comment] 2015-02-18 21:18
Hi @sckott, I thought I figured out how to solve the problem but the Travis builds still aren't working.  Any thoughts? @gavinsimpson @karthik

**Comment by sckott** [comment] 2015-02-18 21:30
looks like it's a diff. problem than before, where both travis (https://travis-ci.org/ropensci/neotoma/builds/46496313#L1027) and appveyor (https://ci.appveyor.com/project/sckott/neotoma/build/1.0.255#L410) say there's a test that's failing - so maybe fix that first, then see if it works after taht

**Comment by gavinsimpson** [comment] 2015-02-18 22:14
It's failing in the `get_geochron` example:

```r
#  Search for sites with "Pseudotsuga" pollen that are older than 8kyr BP and
#  find the relevant radiocarbon ages associated with the cores.
#  Are some time periods better dated than others?
t8kyr.datasets <- get_dataset(taxonname='*Pseudotsuga*', loc=c(-150, 20, -100, 60),
                              ageyoung = 8000)
#  Returns 85 records (as of 01/08/2015).  These are the pollen records though, we want the sites:
geochron.records <- get_geochron(get_site(t8kyr.datasets))

#  We want to extract all the radiocarbon ages from the records:

get_ages <- function(x){
  any.ages <- try(x[[2]]$age[x[[2]]$age.type == 'Radiocarbon years BP'])
  if(class(any.ages) == 'try-error') output <- NA
  if(!class(any.ages) == 'try-error') output <- unlist(any.ages)
  output
}
radio.chron <- unlist(sapply(geochron.records, get_ages))
hist(radio.chron, breaks=seq(0, 40000, by = 500),
     main = 'Distribution of radiocarbon dates for Pseudotsuga records',
     xlab = 'Radiocarbon date (14C years before 1950)')
}
```

I don't know why this isn't failing locally for you as those tests should be being run locally as well as on Travis - I think!?, I don't recall setting this so that only Travis would run those tests!

**Comment by SimonGoring** [comment] 2015-02-18 22:35
Okay, I'll check it out.

**Comment by gavinsimpson** [comment] 2015-02-18 23:57
The `get_download` examples seem to be failing too, at least as far as Appveyor is concerned: https://ci.appveyor.com/project/sckott/neotoma/build/1.0.255#L1864

**Comment by SimonGoring** [comment] 2015-02-19 02:07
Okay, I'm trying to fix the S3 methods issues tonight and I think that'll
fix the travis/appveyor errors too since I'll be cleaning up the tests
anyway.

**Comment by SimonGoring** [comment] 2015-02-20 17:59
Alright!  So, not only have I figured out how Travis and Appveyor work (sort of) I've managed to fix the errors throughout, so I thought everything'd be hunky dory right now.

Having said that, Appveyor seems to be showing a failed build [here](https://ci.appveyor.com/project/sckott/neotoma/build/1.0.264), while travis shows the build passing.  Appveyor seems to choke on the `get_download` example, but that example works for me on my computer and it works in Travis.

@sckott any thoughts on why this is happening?

**Comment by karthik** [comment] 2015-02-20 18:12
@SimonGoring Just getting back up to speed on these (and Open Quarternary) after travels. 
Are appveyor settings set to fail on warnings? Travis appears to not be set up this way (unless you explicitly set it):

```r
env:
  - WARNINGS_ARE_ERRORS=1
```

So maybe that's why its failing?

**Comment by gavinsimpson** [comment] 2015-02-20 18:25
It's failing in a test running the example from `?get_download` on a Windows setup. (Anyone got one of those...?) So there is something weird going on there.

**Comment by SimonGoring** [comment] 2015-02-20 18:31
I'm running this on a windows setup and it passes fine.

**Comment by karthik** [comment] 2015-02-20 18:37
Everything passes fine on my mac, but I get 14 warnings. CI systems can be set to fail on warnings (or explicitly set not to). The travis for this repo appears not to so perhaps that's why its passing and appveyor failing.

**Comment by SimonGoring** [comment] 2015-02-20 18:47
I was looking at some of the things people have posted about failures in appveyor on warnings and I didn't find anything to indicate that appveyor should fail on warnings.  Most of it looked like you'd have to make it do that on purpose.  I don't understand appveyor well enough yet though.

Also, the `last 13 lines of code` shown before the termination are coming from `test_neotoma.R`, not `test_examples.R`, but I assume that's because the `test_examples` get run silently.

**Comment by gavinsimpson** [comment] 2015-02-20 20:37
The log is pretty clear that running the examples are failing on their system:

https://ci.appveyor.com/project/sckott/neotoma/build/1.0.264#L914
https://ci.appveyor.com/project/sckott/neotoma/build/1.0.264#L1468

The message back from **testthat** is:

```
Running the tests in 'tests/test-all.R' failed.
Last 13 lines of output:
  API call was successful. Returned record for Lamb Springs [5DA201]
  API call was successful. Returned record for Blackwater Draw Loc. 1
  .API call was successful. Returned record for Site 30 (Swainunpublished)
  .API call was successful. Returned record for Site 30 (Swainunpublished)
  .
  
  
  1. Failure(@test_examples.R#29): Examples run without error --------------------
  Error raised in example: get_download isn't false
  
  Error: Test failures
```

The way `tests/test_examples.R` is written, the message printed:

    Error raised in example: get_download isn't false

is being produced by running the `get_download` example.

> Also, the last 13 lines of code shown before the termination are coming from test_neotoma.R, not test_examples.R, but I assume that's because the test_examples get run silently.

IIRC, **testthat** will accumulate errors and report about all errors and only throw an error at the end if there was an error. hence you get to see all the errors rather than the first, fix that, retest and see the next.

Easiest way to test this will be to comment out all the code in `tests/test_examples.R` commit that change and see what Appveyor thinks about it.

**Comment by gavinsimpson** [comment] 2015-02-20 20:40
PS @SimonGoring what are all those warnings? Are you calling `warning()` in the code? Might be nicer to just call `message()` if the things you are warning about are not really warnings - somethings not right and I made just have done something BAD - but instead are just FYI, I needed to fix something up in this download/data set/site.

**Comment by gavinsimpson** [comment] 2015-02-20 20:54
OK, so looking through the [log I see](https://ci.appveyor.com/project/sckott/neotoma/build/1.0.264#L1089) [In the snippet below, the presence of 4 dots `....` is where I have trimmed the output.]

```
API call was successful. Returned record for Little Lake (US:Oregon)
Warning: 
Modifiers are absent from the lab objects Lycopodium tablets, Sample quantity, Lycopodium spike. 
get_download will use uniqueidentifiers to resolve the problem.
Error in fromJSON(content, handler, default.size, depth, allowComments,  : 
  invalid JSON input
In addition: Warning messages:
1: In FUN(X[[3L]], ...) : 
The following taxa could not be found in the existing conversion table:
Apiaceae
....
The following taxa could not be found in the existing conversion table:
Indeterminable
The following taxa could not be found in the existing  [... truncated]
2: In FUN(X[[3L]], ...) : 
The following taxa could not be found in the existing conversion table:
Pteridium-type
....
The following taxa could not be found in the existing conversion table:
Arceuthobium
The following taxa could not be found in the  [... truncated]
4: In FUN(X[[1L]], ...) : 
The following taxa could not be found in the existing conversion table:
Ericaceae
....
The following taxa could not  [... truncated]
API call was successful. Returned record for Mosquito Lake Bog
```

I think this means the error is happening in the download for **Little Lake (US:Oregon)** and the error is coming from `fromJSON()`. Looking at `get_download.default`, [you are doing](https://github.com/ropensci/neotoma/blob/master/R/get_download.R#L89-L93):

```r
    aa <- try(fromJSON(paste0(base.uri, '/', x), nullValue = NA))

    # Might as well check here for error and bail
    if (inherits(aa, "try-error"))
        return(aa)
```

which is inside the `get_sample()` in-line function defined in `get_download.default`. That is the only place that `fromJSON` is used in that function. That doesn't mean `get_download.default()` isn't calling something else that is also using that function and throwing the error.

**Comment by SimonGoring** [comment] 2015-02-20 21:00
I don't think that's the problem.  There's warnings thrown elsewhere that
don't cause problems.  It's showing invalid JSON input, so maybe it's
something with the character set in Marion Lake (which seems to be the site
it keeps choking on).

Simon

**Comment by SimonGoring** [comment] 2015-02-20 21:19
Any chance [this](https://github.com/hadley/ggplot2/issues/1056) is related:

https://github.com/hadley/ggplot2/issues/1056

**Comment by gavinsimpson** [comment] 2015-02-20 21:29
The error is either in `Little Lake (US:Oregon)` or `Mosquito Lake Bog` as those are the two API calls that bracket the Error (at least the `fromJSON()` error). Where are you seeing Marion Lake?

If you want a second opinion, through the source tarball at Uwe's [WinBuilder system](http://win-builder.r-project.org/) and see if it generates an error.

But rather than guess, do as I suggested and comment out either L15 in [`tests/test_exmaple.R`](https://github.com/ropensci/neotoma/blob/master/tests/testthat/test_examples.R#L15) or the entire file. Commit that change and see what happens with the Appveyor build.

I'll eat my hat if Appveyor still craps out after turning off the checking of examples.

**Comment by gavinsimpson** [comment] 2015-02-20 21:30
>But rather than guess, do as I suggested and comment out either L15 in tests/test_exmaple.R or the entire file. Commit that change and see what happens with the Appveyor build.

I see you're now doing that....

**Comment by SimonGoring** [comment] 2015-02-20 21:33
:)

Yeah, in the dataset list "Marion Lake" is immediately between Little Lake
and Mosquito lake, so I think it's working for Little Lake, throws an error
for Marion, then works again for Mosquito?  I'm not sure, but Marion Lake
should be in between the two since it's in between them in the dataset
order.

**Comment by gavinsimpson** [comment] 2015-02-20 21:42
OK, so the error is now indicated to be in `get_geochron()`: https://ci.appveyor.com/project/sckott/neotoma/build/1.0.266#L1300

@SimonGoring can you comment out all the code in `tests/test_examples.R`, and **make no other changes**, commit that and we can see if that cures the build problem. If it does, we can start narrowing it down. But only make one change at a time.

**Comment by SimonGoring** [comment] 2015-02-20 21:53
Done.

**Comment by SimonGoring** [comment] 2015-02-20 22:03
Okay, so it passes.  Done and done.  I'll leave the `test_examples.R` for my local builds and ignore it for CRAN?

**Comment by gavinsimpson** [comment] 2015-02-20 22:06
@SimonGoring No, you've gotten this backwards. These tests are there to see when we break things. We want these on on the CI. What we need to do is stop them running on CRAN and I haven't done that bit yet, but I believe `testthat` now has an easy-to-use option for this, so reinstate the example checking and I'll figure out how to tickle testthat to do what we want.

Better would be to work out what is failing. You could uncomment everything except get_geochron now and see if that fails. We can't ignore this.

**Comment by SimonGoring** [comment] 2015-02-20 22:09
Sorry, I was joking.  Yes, the problem now is that it's apparently both `get_geochron` and `get_download`.

So I did change `test_neotoma.R` in the second to last commit and added all the datasets around the failure in `get_download`, but that apparently didn't fail, so . . . weird.

**Comment by SimonGoring** [comment] 2015-02-20 22:23
Okay, so it's just `get_download` and `get_geochron`.  I'll go look at them to see if I can figure out what the problem is.

**Comment by SimonGoring** [comment] 2015-02-26 04:04
Okay, @sckott @karthik Appveyor is still failing, and it's failing on 8+ downloads, but not <7 downloads.  Same fromJSON error, I wonder if Appveyor is doing something that truncates the JSON if the call is taking too long?  Or if there's just a timeout on the appveyor side?  Either way, around all the other things I was doing I got Appveyor to pass each time I ran the checks with <7 downloads, regardless of location.  Failed every time the number was > 8.

Should I just make the tests pull less than 8?  It seems to check fine locally in those cases.  I'd rather it passed on full examples, but if we can't figure it out then maybe it's the best option @gavinsimpson

**Comment by gavinsimpson** [comment] 2015-02-26 04:12
@SimonGoring The Travis CI build is now failing too so I suggest that problem gets fixed first and then reduce the size of the tests.

**Comment by SimonGoring** [comment] 2015-02-26 04:35
That problem looks like the API call got truncated at some point, it's
inside a JSON/Curl call, not explicitly part of the actual package.

**Comment by gavinsimpson** [comment] 2015-02-27 05:15
@SimonGoring I'm close to having gotten this tracked down to a few calls in `test_neotom.R`. Had hoped to finish this this evening but Travis is being slow to bootstrap the R instance for testing.

A few more iterations and I'll have this narrowed down, but may have to wait until tomorrow if Travis doesn't pull it's finger out.

I've also updated the r-Travis config to the new native R support and made the test that runs the examples not get checked/run when on CRAN.

**Comment by karthik** [comment] 2015-02-27 19:15
> I've also updated the r-Travis config to the new native R support and
made the test that runs the examples not get checked/run when on CRAN.

I don't see these anywhere. Are these local changes yet to be pushed?

**Comment by SimonGoring** [comment] 2015-02-27 19:16
Thanks Gavin!

**Comment by gavinsimpson** [comment] 2015-02-27 19:24
@karthik Not here, as I'm beginning to wonder if the Travis build errors are random, but you can see these in my clone: https://github.com/gavinsimpson/neotoma/tree/update-testing, where we now just have

```yaml
language: r

notifications:
  slack:
    secure: random-stuff-here
```

See: https://github.com/gavinsimpson/neotoma/blob/update-testing/.travis.yml

**Comment by SimonGoring** [comment] 2015-04-30 18:55
Hello @karthik @gavinsimpson @sckott, things are passing now, but as @gavinsimpson pointed out, he had to comment out a lot of code for it to work.  Having said that, the package passes the tests locally.

I'm wondering if we want to do any more work on this, or if it's enough to just leave the tests local and close this issue.  Thoughts?

**Comment by gavinsimpson** [comment] 2015-04-30 19:21
@SimonGoring At the very least, build the tarball and submit it to WinBuilder for both current and R Devel versions (you need to do this twice, once per version - and no idea if devtools can do this for you). If things are working without Notes, Warnings, Errors there, then we can probably be certain it will work on the main CRAN test farm.

Once you get the test results back can you post links here so I can take a quick gander?

I'm not fully convinced my test code will not run on CRAN - we don't want it to as the examples take far too long to run and the pkg will be rejected.

If this works, OK push it to CRAN but we need to revisit the failures. If these are due to dodgy characters and it depends on the locale where the code is running we need to address that.

**Comment by gavinsimpson** [comment] 2015-04-30 19:21
URL for win-builder is: http://win-builder.r-project.org/

**Comment by SimonGoring** [comment] 2015-04-30 19:40
I just sent it to win-builder using the `devtools::build_win()`  When I get the email I'll post the reply here.

**Comment by gavinsimpson** [comment] 2015-05-01 17:39
I've run `R CMD check` using R 3.2-patched and I turned on all the tests in `tests/testthat/test_neotoma.R` (with one exception) and we're getting lots of failures, most of which suggest problems with the code that we are not catching because the examples are turned off in the Rd files and don't stretch the uses of **neotoma** and because we (I) had temporarily turned off these tests a while back because Travis was failing for unknown reasons.

See #176 for the gory details.

**Comment by SimonGoring** [comment] 2016-07-07 03:51
Closing this as we seem to have no package side errors any more thanks to everyone's ongoing help :)

**Closed by SimonGoring** 2016-07-07 03:51 UTC
