### ISSUE TITLE
`chronology.id` in `age.type` column? 

### ISSUE THREAD

**Issue by andydawson** [ropensci/neotoma#197] opened 2015-07-14 20:51 UTC
Not sure what is going on here, or if this is an intended update. For the sites I have tried (and maybe all sites), the chronology identification number now appears in the `age.type` column instead of the `chronology.id` column in the objects returned by `get_download`.

For example:

```
foo = get_download(3031)

> foo[[1]]$sample.meta[1:4,]
    depth thickness age.older age age.younger dataset.id                 chronology.name age.type
2     650       0.5        NA -25          NA     NAPD 2 Calibrated radiocarbon years BP     5317
210   662       0.5        NA -13          NA     NAPD 2 Calibrated radiocarbon years BP     5317
3     670       0.5        NA   0          NA     NAPD 2 Calibrated radiocarbon years BP     5317
4     680       0.5        NA  22          NA     NAPD 2 Calibrated radiocarbon years BP     5317
    sample.id chronology.id unit.name
2       56805            NA        NA
210     56807            NA        NA
3       56809            NA        NA
4       56811            NA        NA

> foo[[1]]$chronologies[[1]][1:4,]
  age.older age age.younger     dataset.id      chronology.name age.type chronology.id
1        NA   0          NA COHMAP chron 1 Radiocarbon years BP     1353            NA
2        NA  21          NA COHMAP chron 1 Radiocarbon years BP     1353            NA
3        NA  36          NA COHMAP chron 1 Radiocarbon years BP     1353            NA
4        NA  54          NA COHMAP chron 1 Radiocarbon years BP     1353            NA
```

Is this intentional?

**Comment by SimonGoring** [comment] 2015-07-15 01:19
Yeah, that's a bug.  I'm not sure why it's happened all of a sudden, although I suspect it comes from differences in the API between different data set types.  I need to double check, but I thought I tried to fix this by using explicit calls to the column names.  The problem is clearly that `dataset.id` is getting the wrong information, and then everything is shifted over.  I'll try to fix this ASAP.

**Comment by andydawson** [comment] 2015-07-15 02:10
Thanks @SimonGoring. I'm also confused by this one!

**Comment by SimonGoring** [comment] 2015-07-15 02:11
This is now resolved by commit 83e7441.  I've added tests to ensure it won't happen again.  Use `install_github('ropensci/neotoma)` and everything should be fine.

**Closed by SimonGoring** 2015-07-15 02:11 UTC

**Comment by andydawson** [comment] 2015-07-15 02:12
Awesome, that was fast! Can you fix all my other (non-neotoma) problems too? :)

**Comment by SimonGoring** [comment] 2015-07-15 02:15
Easy. Fixed in commit
83838828282838383838191291291921929191919192191912491291249239234293492349ddd912312391239123912312.
You just have to figure out which repository I used :)
